version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "firstapp"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "database"
  app-backend:
    image: vorstu/first_app_backend:0.0.1-SNAPSHOT
    environment:
      DATABASESERVER_PORT: "5432"

    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
  app-frontend:
    image: vorstu/first_app_frontend

    depends_on:
      app-backend:
        condition: service_started
    ports:
      - "8081:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge